# Generated by Django 3.0.6 on 2020-05-13 22:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PostMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boast', models.BooleanField(default=True, verbose_name='boast?')),
                ('roast', models.BooleanField(default=False, verbose_name='roast?')),
                ('content', models.CharField(max_length=280)),
                ('up_vote', models.IntegerField()),
                ('down_vote', models.IntegerField()),
                ('sub_time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
