# Generated by Django 3.0.6 on 2020-05-15 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ghostpost', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmessage',
            name='score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='postmessage',
            name='down_vote',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='postmessage',
            name='up_vote',
            field=models.IntegerField(default=0),
        ),
    ]
